services:
    #Override bitbag product bundle Controller
    nobless_order_item_controller:
        class: App\Controller\Shop\OrderItemController
        parent: 'bitbag_sylius_product_bundle.controller.order_item'
        arguments: ['@sylius.custom_factory.order_item', '@session']
