imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@BitBagSyliusProductBundlePlugin/Resources/config/config.yml" }
    
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/config.yml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_addressing:
    resources:
        address:
            classes:
                model: App\Entity\Addressing\Address
        country:
            classes:
                model: App\Entity\Addressing\Country
        province:
            classes:
                model: App\Entity\Addressing\Province
        zone:
            classes:
                model: App\Entity\Addressing\Zone
        zone_member:
            classes:
                model: App\Entity\Addressing\ZoneMember

sylius_admin_api:
    resources:
        api_client:
            classes:
                model: App\Entity\AdminApi\Client
        api_access_token:
            classes:
                model: App\Entity\AdminApi\AccessToken
        api_refresh_token:
            classes:
                model: App\Entity\AdminApi\RefreshToken
        api_auth_code:
            classes:
                model: App\Entity\AdminApi\AuthCode

sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: App\Entity\Product\ProductAttribute
                translation:
                    classes:
                        model: App\Entity\Product\ProductAttributeTranslation
            attribute_value:
                classes:
                    model: App\Entity\Product\ProductAttributeValue

sylius_channel:
    resources:
        channel:
            classes:
                model: App\Entity\Channel\Channel
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\Product\ProductImage
        taxon_image:
            classes:
                model: App\Entity\Taxonomy\TaxonImage
        product_taxon:
            classes:
                model: App\Entity\Product\ProductTaxon
        channel_pricing:
            classes:
                model: App\Entity\Channel\ChannelPricing

sylius_currency:
    resources:
        currency:
            classes:
                model: App\Entity\Currency\Currency
        exchange_rate:
            classes:
                model: App\Entity\Currency\ExchangeRate

sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\Customer\Customer
                controller: App\Controller\Shop\UserController
        customer_group:
            classes:
                model: App\Entity\Customer\CustomerGroup

sylius_locale:
    resources:
        locale:
            classes:
                model: App\Entity\Locale\Locale

sylius_order:
    resources:
        order:
            classes:
                model: App\Entity\Order\Order
        order_item:
            classes:
                model: App\Entity\Order\OrderItem
        order_item_unit:
            classes:
                model: App\Entity\Order\OrderItemUnit
        adjustment:
            classes:
                model: App\Entity\Order\Adjustment
        order_sequence:
            classes:
                model: App\Entity\Order\OrderSequence

sylius_payment:
    resources:
        payment_method:
            classes:
                model: App\Entity\Payment\PaymentMethod
            translation:
                classes:
                    model: App\Entity\Payment\PaymentMethodTranslation
        payment:
            classes:
                model: App\Entity\Payment\Payment

sylius_payum:
    resources:
        payment_security_token:
            classes:
                model: App\Entity\Payment\PaymentSecurityToken
        gateway_config:
            classes:
                model: App\Entity\Payment\GatewayConfig

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product
                repository: App\Repository\ProductRepository
            translation:
                classes:
                    model: App\Entity\Product\ProductTranslation
        product_variant:
            classes:
                model: App\Entity\Product\ProductVariant
                repository: BitBag\SyliusProductBundlePlugin\Repository\ProductVariantRepository
            translation:
                classes:
                    model: App\Entity\Product\ProductVariantTranslation
        product_option:
            classes:
                model: App\Entity\Product\ProductOption
            translation:
                classes:
                    model: App\Entity\Product\ProductOptionTranslation
        product_option_value:
            classes:
                model: App\Entity\Product\ProductOptionValue
            translation:
                classes:
                    model: App\Entity\Product\ProductOptionValueTranslation
        product_association:
            classes:
                model: App\Entity\Product\ProductAssociation
        product_association_type:
            classes:
                model: App\Entity\Product\ProductAssociationType
            translation:
                classes:
                    model: App\Entity\Product\ProductAssociationTypeTranslation

sylius_promotion:
    resources:
        promotion:
            classes:
                model: App\Entity\Promotion\Promotion
        promotion_rule:
            classes:
                model: App\Entity\Promotion\PromotionRule
        promotion_action:
            classes:
                model: App\Entity\Promotion\PromotionAction
        promotion_coupon:
            classes:
                model: App\Entity\Promotion\PromotionCoupon

sylius_review:
    resources:
        product:
            review:
                classes:
                    model: App\Entity\Product\ProductReview

sylius_shipping:
    resources:
        shipment:
            classes:
                model: App\Entity\Shipping\Shipment
        shipping_method:
            classes:
                model: App\Entity\Shipping\ShippingMethod
            translation:
                classes:
                    model: App\Entity\Shipping\ShippingMethodTranslation
        shipping_category:
            classes:
                model: App\Entity\Shipping\ShippingCategory

sylius_taxation:
    resources:
        tax_category:
            classes:
                model: App\Entity\Taxation\TaxCategory
        tax_rate:
            classes:
                model: App\Entity\Taxation\TaxRate

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: App\Entity\User\AdminUser
        shop:
            user:
                classes:
                    model: App\Entity\User\ShopUser
                    controller: App\Controller\Shop\UserController
        oauth:
            user:
                classes:
                    model: App\Entity\User\UserOAuth

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"

sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            class: primary
                            icon: plus
                            header:
                                icon: cube
                                label: sylius.ui.type
                            links:
                                simple:
                                    label: sylius.ui.simple_product
                                    icon: plus
                                    route: sylius_admin_product_create_simple
                                configurable:
                                    label: sylius.ui.configurable_product
                                    icon: plus
                                    route: sylius_admin_product_create
                                bundle:
                                    label: bitbag_sylius_product_bundle.ui.bundle
                                    icon: plus
                                    route: bitbag_product_bundle_admin_product_create_bundle
        sylius_shop_account_order:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.order.class%"
                    repository:
                        method: createByCustomerAndChannelIdQueryBuilder
                        arguments:
                            - "expr:service('sylius.context.customer').getCustomer().getId()"
                            - "expr:service('sylius.context.channel').getChannel().getId()"
            sorting:
                checkoutCompletedAt: desc
            fields:
                number:
                    type: twig
                    label: sylius.ui.number
                    sortable: false
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/number.html.twig"
                checkoutCompletedAt:
                    type: datetime
                    label: sylius.ui.date
                    sortable: false
                    options:
                        format: m/d/Y
                shippingAddress:
                    enabled: false
                    type: twig
                    label: sylius.ui.ship_to
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/address.html.twig"
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: false
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/state.html.twig"
                        vars:
                            labels: "@SyliusShop/Account/Order/Label/State"
                    position: 3
                shipments:
                    type: twig
                    label: sylius.ui.tracking_number
                    sortable: false
                    options: 
                        template: "@SyliusShop/Account/Order/Grid/Field/shipment_number.html.twig"
                    position: 4
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: false
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/total.html.twig"
                    position: 5
            actions:
                item:
                    show:
                        type: shop_show
                        label: sylius.ui.show_order
                        options:
                            template: "@SyliusShop/Account/Order/Grid/Action/show.html.twig"
                            link:
                                route: sylius_shop_account_order_show
                                parameters:
                                    number: resource.number
                    pay:
                        enabled: false
                        type: shop_pay
                        label: sylius.ui.pay
                        options:
                            link:
                                route: sylius_shop_order_show
                                parameters:
                                    tokenValue: resource.tokenValue

liip_imagine:
    filter_sets:
        sylius_shop_product_vertical_thumbnail:
            filters:
                thumbnail: { size: [500, 637], mode: outbound }
        sylius_shop_product_gallery:
            filters:
                thumbnail: { size: [400, 600], mode: outbound }
        sylius_shop_product_large_gallery:
            filters:
                thumbnail: { size: [981, 1500], mode: outbound }
        sylius_shop_product_mobile_thumbnail:
            filters:
                thumbnail: { size: [500, 750], mode: outbound }
        sylius_shop_slider_mobile_thumbnail:
            filters:
                thumbnail: { size: [800, 800], mode: outbound }
        sylius_shop_order_info_thumbnail:
            filters:
                thumbnail: { size: [112, 150], mode: outbound }
                
mobile_detect:
    service:
        mobile_detector: mobile_detect.mobile_detector.default
    device_view_class: SunCat\MobileDetectBundle\Helper\DeviceView
    request_response_listener_class: SunCat\MobileDetectBundle\EventListener\RequestResponseListener
    twig_extension_class: SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension
