sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_contact_request:
    resource: "../routing/contact.yml"
    prefix: /{_locale}/contact
    
sylius_shop_checkout:
    resource: "../routing/checkout.yml"
    prefix: /{_locale}/checkout
    
sylius_shop_cart:
    resource: "../routing/cart.yml"
    prefix: /{_locale}/cart

sylius_shop_account:
    resource: "../routing/account.yml"
    prefix: /{_locale}/account

sylius_shop_ajax_cart:
    resource: "../routing/ajax/cart.yml"
    prefix: /{_locale}/cart
    
sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

sylius_shop_request_password_reset_token:
    path: /{_locale}/forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/passwordResetModal.html.twig"
            redirect: sylius_shop_login

sylius_shop_login:
    path: /{_locale}/login
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.security:loginAction
        _sylius:
            template: "@SyliusShop/login.html.twig"
            logged_in_route: sylius_shop_account_dashboard

sylius_shop_to_register:
    path: /{_locale}/to-register
    methods: [POST, GET]
    defaults:
        _controller: sylius.controller.shop.register:toRegisterAction
        _sylius:
            logged_in_route: sylius_shop_account_dashboard
            
sylius_shop_product_index:
    path: /{_locale}/taxons/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            maxPerPage: 12
            template: "@SyliusShop/Product/index.html.twig"
            grid: sylius_shop_product
    requirements:
        slug: .+

# Bitbag override
bitbag_sylius_product_bundle_shop_partial_cart_add_product_bundle:
    path: /_partial/cart/product-bundle/add
    methods: [GET]
    defaults:
        _controller: bitbag_custom_order_item_controller:addProductBundleAction
        _sylius:
            template: $template
            factory:
                method: createForProduct
                arguments: [expr:notFoundOnNull(service('sylius.repository.product').find($productId))]
            form:
                type: App\Form\Extension\BitBagAddProductBundleToCartType
                options:
                    product: expr:notFoundOnNull(service('sylius.repository.product').find($productId))
                    data_class: App\Component\ProductBundle\AddProductBundleToCartCommand
            redirect:
                route: sylius_shop_cart_summary
                parameters: {}

bitbag_sylius_product_bundle_shop_ajax_cart_add_product_bundle:
    path: /ajax/cart/product-bundle/add
    methods: [POST]
    defaults:
        _controller: bitbag_custom_order_item_controller:addProductBundleAction
        _format: json
        _sylius:
            factory:
                method: createForProduct
                arguments: [expr:notFoundOnNull(service('sylius.repository.product').find($productId))]
            form:
                type: App\Form\Extension\BitBagAddProductBundleToCartType
                options:
                    product: expr:notFoundOnNull(service('sylius.repository.product').find($productId))
                    data_class: App\Component\ProductBundle\AddProductBundleToCartCommand
            redirect:
                route: sylius_shop_cart_summary
                parameters: {}
            flash: sylius.cart.add_item
