bitbag_sylius_product_bundle_plugin:
    resource: "@BitBagSyliusProductBundlePlugin/Resources/config/routing.yml"

bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"

app_shop_latest_products:
    path: /latest/products
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.homepage:latestProductsAction

app_shop_latest_bundles:
    path: /latest/bundles
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.homepage:latestBundlesAction
