# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: services/ }

parameters:
    locale: fr_FR

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Twig}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sylius.controller.shop.homepage:
        class: App\Controller\Shop\HomepageController
        arguments: ['@templating']

    sylius.controller.shop.product:
        class: App\Controller\Shop\ProductController
        arguments: [ '@templating']

    sylius.controller.shop.locale_switch:
        class: App\Controller\Shop\LocaleSwitchController
        arguments: ['@templating', '@sylius.context.locale', '@sylius.locale_provider', '@sylius.shop.locale_switcher']
    
    sylius.controller.shop.security:
        class: App\Controller\Shop\SecurityController
        arguments: ['@security.authentication_utils', '@form.factory', '@templating', '@security.authorization_checker', '@router']
    
    sylius.controller.shop.register:
        class: App\Controller\Shop\RegisterController
        arguments: ['@security.authentication_utils', '@form.factory', '@templating', '@security.authorization_checker', '@router']

    # Forms
    app.form.type.register_login:
        class: App\Form\RegisterLoginType
        tags:
            - { name: form.type }

    app.form.extension.customer_registration:
        class: App\Form\Extension\CustomerRegistrationTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType }

    app.form.extension.customer_profile:
        class: App\Form\Extension\CustomerProfileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType }

    app.form.extension.address:
        class: App\Form\Extension\AddressTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType }

    #Menu
    app.listener.shop.menu_builder:
        class: App\Menu\AccountMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }

    #Grid Filters
    app.grid.filter.size:
        class: App\Grid\Filter\SizeFilter
        tags:
            -   name: sylius.grid_filter
                type: size
                form_type: App\Form\Type\Filter\SizeFilterType

    app.grid.filter.price:
        class: App\Grid\Filter\PriceFilter
        arguments: 
            -   '@doctrine.orm.entity_manager'
            -   "@request_stack"
            -   "@sylius.context.locale"
            -   "@sylius.repository.taxon"
        tags:
            -   name: sylius.grid_filter
                type: price
                form_type: App\Form\Type\Filter\PriceFilterType

    #Twig Extensions
    app.twig.extension.product_variants:
        class: App\Twig\Extension\ProductVariants
        arguments:
            - '@twig'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }
